spring:
  application:
    name: bankApi
  profiles:
    active: dev
  messages:
    basename: messages
    encoding: UTF-8

flyway:
  enabled: true
  baseline-on-migrate: true

security:
  jwt:
    acess-token:
      expiration: 600
    refresh-token:
      expiration: 20000

scheduler:
  fraud-scan: 300000
  token-clean: 300000

fraud:
  threshold: 20000.00
  transaction-count: 3
  window-minutes: 5