package com.github.freddy.bankApi.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    NOT_FOUND,
    INSUFFICIENT_FUNDS,
    UNAUTHORIZED,
    CONFLICT,
    ACCOUNT_CREATION_ERROR,
    INVALID_REFERENCE_CODE
}
